# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
sudo: false
cache: packages
cran: https://cran.rstudio.com/
warnings_are_errors: false
r_check_args: '--as-cran'

matrix:
  include:
  - r: bioc-devel
    after_success:
    - Rscript -e 'covr::codecov()'

before_cache: Rscript -e 'remotes::install_dev("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
